<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.6</version>
        <relativePath/>
    </parent>

    <groupId>com.tungdt.microservices</groupId>
    <artifactId>java-microservices</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>src/common</module>
        <module>src/gateway-service</module>
        <module>src/Services/identity-service</module>
        <module>src/Services/product-service</module>
        <module>src/Services/customer-service</module>
        <module>src/Services/basket-service</module>
        <module>src/Services/ordering-service</module>
        <module>src/Services/inventory-service</module>
        <module>src/background-job-service</module>
        <module>src/Services/email-service</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <spring-cloud.version>2023.0.4</spring-cloud.version>
        <springdoc.version>2.7.0</springdoc.version>
        <spring-boot.repackage.skip>false</spring-boot.repackage.skip>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <skip>${spring-boot.repackage.skip}</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
