server:
  port: 5001

spring:
  application:
    name: identity-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1434;databaseName=master;encrypt=false;trustServerCertificate=true}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

app:
  security:
    enabled: ${APP_SECURITY_ENABLED:false}
    issuer-uri: ${APP_SECURITY_ISSUER_URI:http://localhost:8080/realms/microservices}
    audiences:
      - ${APP_SECURITY_AUDIENCE:microservices-api}
    client-id: ${APP_SECURITY_CLIENT_ID:identity-service}

management:
  endpoints:
    web:
      exposure:
        include: health,info
