[SERVICE]
    Flush            5
    Daemon           Off
    Log_Level        info
    Log_File         /var/log/fluent-bit/internal.log
    Parsers_File     parsers.conf
    storage.path     /fluent-bit/storage

[INPUT]
    Name             tail
    Path             /var/lib/docker/containers/*/*.log
    Parser           docker
    Tag              docker.local
    Path_Key         source_file
    DB               /fluent-bit/storage/docker-logs.db
    Mem_Buf_Limit    20MB
    Skip_Long_Lines  On
    Refresh_Interval 5

[FILTER]
    Name             modify
    Match            docker.local
    Add              environment local

[OUTPUT]
    Name                 es
    Match                docker.local
    Host                 elasticsearch
    Port                 9200
    Logstash_Format      On
    Logstash_Prefix      microservices
    Suppress_Type_Name   On
    Retry_Limit          False
